import {useRef,useState} from 'react';
import {merchants,dishes,type Dish,type Post} from './data';
import {Food} from './ui';
import {communityPosts,communityTopics} from './communityFeed';
import {deliveryResults} from './deliverySearch';

export function CommunityHome({posts,liked,followed,onPost,onPublish,variant}:{posts:Post[];liked:string[];followed:string[];onPost:(p:Post)=>void;onPublish:()=>void;variant:string}){
 const searchInput=useRef<HTMLInputElement>(null);
 const [channel,setChannel]=useState('发现');const [query,setQuery]=useState('');const [topic,setTopic]=useState('推荐');
 const list=communityPosts(posts,{query,channel,topic,followed});
 const card=(p:Post)=>{const d=dishes.find(d=>d.id===p.dishId)!;return <button key={p.id} className="post-card" onClick={()=>onPost(p)}><Food art={d.art}/><div className="post-copy"><h3>{p.title}</h3><div className="byline"><span><i>{p.author[0]}</i>{p.author}</span><span className={liked.includes(p.id)?'hearted':''}>♡ {liked.includes(p.id)?'已收藏':'看看'}</span></div></div></button>;};
 return <><nav className="community-channels" aria-label="内容频道"><button className="publish-mini" aria-label="发布食记" onClick={onPublish}>＋</button>{['关注','发现','同城'].map(c=><button key={c} className={channel===c?'active':''} onClick={()=>setChannel(c)}>{c}</button>)}<button aria-label="搜索食记" onClick={()=>searchInput.current?.focus()}>⌕</button></nav><label className="search home-search">⌕ <input ref={searchInput} aria-label="搜索菜品或门店" placeholder="搜索食记、菜品或门店" value={query} onChange={e=>setQuery(e.target.value)}/></label>{channel==='同城'&&<p className="city-hint">上海 · 静安演示商圈（未读取定位）</p>}<div className="topic-tabs" aria-label="兴趣主题">{communityTopics.map(t=><button className={t===topic?'active':''} key={t} onClick={()=>setTopic(t)}>{t}</button>)}</div>{list.length===0?<div className="empty">{channel==='关注'?'关注一位作者后，就能在这里看到食记。':'没有找到对应食记。'}<button onClick={()=>{setChannel('发现');setQuery('');setTopic('推荐');}}>看看推荐食记</button></div>:variant==='A'?<div className="waterfall"><div>{list.filter((_,i)=>i%2===0).slice(0,8).map(card)}</div><div>{list.filter((_,i)=>i%2===1).slice(0,8).map(card)}</div></div>:<div className={'feed-grid variant-'+variant}>{list.slice(0,12).map(card)}</div>}{list.length>0&&<div className="feed-end">已展示 {Math.min(list.length,variant==='A'?16:12)} 篇精选模拟食记 · 图片为 AI 生成</div>}</>;
}

export function DeliveryHome({onMerchant,onDish}:{onMerchant:(id:string)=>void;onDish:(d:Dish)=>void}){
 const [query,setQuery]=useState('');const [category,setCategory]=useState(-1);const [sort,setSort]=useState('综合');const [area,setArea]=useState('全部');
 const categories=[['全部','⌂'],['吃饭','🍚'],['甜品','🍮'],['饮品','☕'],['面食','🍜']];
 const ordered=deliveryResults({query,category,area,sort});
 return <><div className="delivery-home-top"><div className="address-row"><strong>推荐</strong><label>送至 <select aria-label="演示配送区域" value={area} onChange={e=>setArea(e.target.value)}><option value="全部">演示地址 · 上海</option><option value="静安">静安演示商圈</option><option value="徐汇">徐汇演示商圈</option></select></label></div><form className="delivery-search" onSubmit={e=>{e.preventDefault();document.querySelector('.merchant-list')?.scrollIntoView({behavior:'smooth',block:'nearest'});}}>⌕ <input aria-label="搜索吃了么门店或菜品" placeholder="想吃什么？搜店名或菜名" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit">搜索</button></form></div><div className="category-grid">{categories.map(([name,icon],i)=><button className={category===[-1,0,1,2,3][i]?'active':''} key={name} onClick={()=>setCategory([-1,0,1,2,3][i])}><span>{i===0?icon:<Food art={[0,0,5,2,3][i]} small/>}</span>{name}</button>)}</div>{!query.trim()&&category===-1&&area!=='徐汇'&&<button className="pudding-banner" onClick={()=>onDish(dishes[1])}><div><small>今天，甜一点</small><h2>这一口，先看再点</h2><p>焦糖布丁 · 社区食记可查看</p><b>看看这道菜 →</b></div><Food art={1} small/></button>}<div className="merchant-filters"><button className={sort==='综合'?'active':''} onClick={()=>setSort('综合')}>综合推荐</button><button className={sort==='价格'?'active':''} onClick={()=>setSort('价格')}>价格友好</button><span>价格 / 配送为模拟</span></div><div className="merchant-list">{ordered.length?ordered.map(({merchant:m,menu,minPrice})=>{return <button className="merchant-card" key={m.id} onClick={()=>onMerchant(m.id)}><Food art={menu[0].art} small/><div><h3>{m.name}（{m.branch}）</h3><p><b>约 30 分钟</b> · 演示配送</p><p>¥{minPrice} 起 <span>模拟免配送费</span></p><div className="merchant-tags"><span>{menu.slice(0,2).map(d=>d.name).join(' · ')}</span></div><small>{query.trim()||category>=0?'匹配 '+menu.length+' 道菜 · 查看菜单 →':'查看菜单及菜品评价 →'}</small></div></button>}):<div className="empty">没有符合条件的门店<button onClick={()=>{setQuery('');setCategory(-1);setArea('全部');}}>重置筛选</button></div>}</div></>;
}
